name: gitflow-automation
on:
  pull_request:
    types: [closed]
jobs:
  create-auto-pr:
    name: Gitflow Automation
    runs-on: ubuntu-latest
    env:
    steps:
      - name: gitflow-automation
        uses: peoplefund-tech/gitflow-automation@v0.1.1
        env:
          BRANCH_PREFIX: "hotfix/"
          TARGET_BRANCH: "develop"
          BASE_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # 선택사항
